name: tmol
dependencies:
  # Core dev requirements
  - python=3.5
  - ipython
  - ipykernel
  - numpy
  - pandas
  - h5py
  - scipy
  - biopython
  - numba
  - requests

  # Torch source-install requirements
  - pyyaml
  - mkl==11.3.3
  - cmake
  - cffi
  - setuptools
